#!/usr/bin/env bash

_program()
{
	core_usesIn core/variable array
	core_uses fatten
	fatten()
	{
		fatten_discoverPackageManagers
		fatten_obtainGitDetails
		fatten_createTemporaryFolder
		fatten_createOutputFolder
		
		core_variable_array_iterate fatten_programs fatten_fattenProgram
	}
}

_program_name='fatten'
_program_namespace='fatten'
_program_version='unversioned'
_program_package_or_build=''
_program_copyright='(c) 2014 Raphael Cohn'
_program_licence='MIT'
_program_written_by='Raphael Cohn'
_program_path="$([ "${_program_fattening_program_path+set}" = 'set' ] && printf '%s\n' "$_program_fattening_program_path" || ([ "${0%/*}" = "${0}" ] && printf '%s\n' '.' || printf '%s\n' "${0%/*}"))"
_program_libPath="${_program_path}/lib"
_program_etcPath="${_program_path}/etc"
_program_varPath="${_program_path}/var"
_program_entrypoint='fatten'

_program_commandLine_parseInitialise()
{
	# Needed in help text
	_program_default_etcPath='/etc'
	_program_default_libPath='/usr/lib'
	_program_default_varPath='/var'
}

_program_commandLine_helpMessage()
{
	_program_commandLine_helpMessage_usage="[OPTION]... -- [PROGRAMS]..."
	_program_commandLine_helpMessage_description="Fattens shellfire executables so they standalone."
	_program_commandLine_helpMessage_options="
  -r, --repository-path PATH  Path to folder containing a PROGRAM
  -e, --etc-path PATH         Path to install fir etc folder [Default ${_program_default_etcPath}]
  -l, --lib-path PATH         Path to lib folder [Default ${_program_default_libPath}]
  -l, --var-path PATH         Path to var folder [Default ${_program_default_varPath}]
  -f, --force                 Force fattening even if there are uncommited changes
  -o, --output-path PATH      Path to folder (created in necessary) for fattened PROGRAM"
    _program_commandLine_helpMessage_optionsSpacing='     '
	_program_commandLine_helpMessage_configurationKeys="
  fatten_etcPath  Equivalent to --etc-path
  fatten_libPath  Equivalent to --lib-path
  fatten_varPath  Equivalent to --var-path
  fatten_repositoryPath  Equivalent to --repository-path
  fatten_force  Equivalent to --force (specify yes or no)
  fatten_outputPath  Equivalent to --output-path
"
	_program_commandLine_helpMessage_examples="
  ${_program_name} -r git-repo/bin -- minor-test
"
}

_program_commandLine_optionExists()
{
	case "$optionName" in
		
		r|repository-path)
			echo 'yes-argumented'
		;;
		
		e|etc-path)
			echo 'yes-argumented'
		;;
		
		f|force)
			echo 'yes-argumentless'
		;;
		
		l|lib-path)
			echo 'yes-argumented'
		;;
		
		l|var-path)
			echo 'yes-argumented'
		;;
		
		o|output-path)
			echo 'yes-argumented'
		;;
		
		*)
			echo 'no'
		;;
		
	esac
}

_program_commandLine_processOptionWithoutArgument()
{
	case "$optionName" in
		
		f|force)
			fatten_force='yes'
		;;
		
	esac
}

_program_commandLine_processOptionWithArgument()
{
	case "$optionName" in
		
		r|repository-path)
			core_validate_folderPathReadableAndSearchable $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			fatten_repositoryPath="$optionValue"
		;;
		
		e|etc-path)
			core_validate_pathNotEmpty $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			fatten_etcPath="$optionValue"
		;;
		
		l|lib-path)
			core_validate_pathNotEmpty $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			fatten_libPath="$optionValue"
		;;
		
		l|var-path)
			core_validate_pathNotEmpty $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			fatten_varPath="$optionValue"
		;;
		
		o|output-path)
			core_validate_pathNotEmpty $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			fatten_outputPath="$optionValue"
		;;
		
		*)
			echo 'no'
		;;
		
	esac
}

_program_commandLine_handleNonOptions()
{
	if [ $# -eq 0 ]; then
		core_commandLine_exitBadCommandLine "No programs specified"
	fi
	local fatten_program
	for fatten_program in "$@"
	do
		core_validate_filePathReadableAndExecutableAndNotEmpty $core_commandLine_exitCode_USAGE 'non-options' 'programs' "$fatten_program"
		
		cd -P "$(core_compatibility_dirname "$fatten_program")" 1>/dev/null
		
			fatten_program="$(pwd)"/"$(core_compatibility_basename "$fatten_program")"
		
		cd - >/dev/null
		
		core_variable_array_append fatten_programs "$fatten_program"
	done
}

_program_commandLine_validate()
{
	local optionNameIncludingHyphens
	local optionValue
	
	if core_variable_isUnset fatten_force; then
		fatten_force='no'
	else
		core_validate_isBoolean $core_commandLine_exitCode_CONFIG 'configuration setting' 'fatten_force' "$fatten_force"
	fi
	
	if core_variable_isUnset fatten_repositoryPath; then
		core_commandLine_exitBadCommandLine "The option '--repository-path (-r)' must be specified"
	else
		core_validate_folderPathReadableAndSearchable $core_commandLine_exitCode_CONFIG 'configuration setting' 'fatten_repositoryPath' "$fatten_repositoryPath"
	fi
	
	if core_variable_isUnset fatten_etcPath; then
		fatten_etcPath="$_program_default_etcPath"
	else
		core_validate_pathNotEmpty $core_commandLine_exitCode_CONFIG 'configuration setting' 'fatten_etcPath' "$fatten_etcPath"
	fi
	
	if core_variable_isUnset fatten_libPath; then
		fatten_libPath="$_program_default_libPath"
	else
		core_validate_pathNotEmpty $core_commandLine_exitCode_CONFIG 'configuration setting' 'fatten_libPath' "$fatten_libPath"
	fi
	
	if core_variable_isUnset fatten_varPath; then
		fatten_varPath="$_program_default_varPath"
	else
		core_validate_pathNotEmpty $core_commandLine_exitCode_CONFIG 'configuration setting' 'fatten_varPath' "$fatten_varPath"
	fi
	
	if core_variable_isUnset fatten_outputPath; then
		core_commandLine_exitBadCommandLine "The option '--output-path (-o)' must be specified"
	else
		core_validate_pathNotEmpty $core_commandLine_exitCode_CONFIG 'configuration setting' 'fatten_outputPath' "$fatten_outputPath"
	fi
}

# Assumes pwd, and so requires this code to be running from this folder
. "$_program_libPath"/shellfire/core/init.functions "$@"
